# Generated by Django 3.2.6 on 2021-08-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriendly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=64)),
                ('url_hotel', models.CharField(max_length=1024)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=12)),
                ('active', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PetFriendly',
        ),
    ]
