# Generated by Django 3.2.6 on 2021-08-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriendly', '0002_auto_20210812_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelslocation',
            name='active',
            field=models.SmallIntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1),
        ),
    ]
