# Generated by Django 3.2.6 on 2021-08-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriendly', '0003_alter_hotelslocation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelslocation',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hotelslocation',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
    ]
