# Generated by Django 3.2.6 on 2021-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriendly', '0004_auto_20210813_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelslocation',
            name='count_park',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelslocation',
            name='count_pet_store',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelslocation',
            name='count_restaurants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelslocation',
            name='count_veterinary_care',
            field=models.IntegerField(default=0),
        ),
    ]
