# Generated by Django 3.2.6 on 2021-08-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriendly', '0005_auto_20210824_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelslocation',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
